
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseLot.java
 *
 * Created on Apr 23, 2014, 2:02:07 PM
 */
/**
 *
 * @author S500900
 */
public class ChooseLot extends javax.swing.JFrame {

    /** Creates new form ChooseLot */
    public ChooseLot() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Choose Lot");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northLot = new javax.swing.JButton();
        southLot = new javax.swing.JButton();
        busLot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        northLot.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        northLot.setText("North Lot");
        northLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                northLotActionPerformed(evt);
            }
        });

        southLot.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        southLot.setText("South Lot");
        southLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southLotActionPerformed(evt);
            }
        });

        busLot.setFont(new java.awt.Font("Georgia", 0, 14));
        busLot.setText("Bus Lot");
        busLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busLotActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36));
        jLabel1.setText("Main Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(busLot, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(southLot, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(northLot, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(northLot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(southLot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busLot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void southLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southLotActionPerformed
        RunProgram.southLot.show();
        RunProgram.currentLot = "South Lot";
        this.show(false);
    }//GEN-LAST:event_southLotActionPerformed

    private void busLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busLotActionPerformed
        RunProgram.busLot.show();
        RunProgram.currentLot = "Bus Lot";
        this.show(false);
    }//GEN-LAST:event_busLotActionPerformed

    private void northLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northLotActionPerformed
        RunProgram.northLot.show();
        RunProgram.currentLot = "North Lot";
        this.show(false);
    }//GEN-LAST:event_northLotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ChooseLot().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busLot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton northLot;
    private javax.swing.JButton southLot;
    // End of variables declaration//GEN-END:variables
}
